peer_id: "data_caller"
data:
  - key: "json_connections"
    target: "target_id"
    type: "string"
    plugins:
      - plugin_name: "string_loopback::StringLoopback"

media:
  gst_script: "gst-launch-1.0 rtpbin name=rtpbin rtp-profile=avpf  v4l2src device=/dev/video0 ! video/x-h264,stream-format=byte-stream,alignment=au,width=1920,height=1080,pixel-aspect-ratio=1/1,framerate=30/1 ! rtph264pay pt=100 mtu=1400		! rtprtxqueue max-size-packets=0 max-size-time=200 ! rtpbin.send_rtp_sink_0		rtpbin.send_rtp_src_0 ! udpsink port=$DEST_VIDEO_RTP_PORT host=$DEST sync=false async=false name=vrtpsink		rtpbin.send_rtcp_src_0 ! udpsink port=$DEST_VIDEO_RTCP_PORT host=$DEST sync=false async=false name=vrtcpsink		udpsrc port=$SRC_VIDEO_RTCP_PORT name=vrtpsrc ! rtpbin.recv_rtcp_sink_0"
